### ISSUE TITLE
Error in single scan (unexistent path)

### ISSUE THREAD

**Issue by secu77** [cyc10n3/WPScan_Web_Interface#2]
Hi,

I've found an error when I run a single scan:

After install wpscan, npm dependencies and run `npm start`. I log in and try to
scan a single target, for example, http://test.com, and I then, the application crashed.
After see npm log error, I could see the following:

```
Scan started on URI: http://www.test.com/
fs.js:121
    throw err;
    ^

Error: ENOENT: no such file or directory, open './data/scan_results/www.test.com_1546469672610.json'
    at Object.openSync (fs.js:450:3)
    at Object.readFileSync (fs.js:350:35)
    at /home/secu/Documentos/github/WPScan_Web_Interface/server.js:240:43
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:188:13)
    at Pipe._handle.close (net.js:610:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! WPScan_Web_Interface@1.0.0 start: node server.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the WPScan_Web_Interface@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
<br>

In the [line](https://github.com/cyc10n3/WPScan_Web_Interface/blob/master/server.js#L233) of server.js, program try to read of an non existing folder, so simple y solve this bug creating `scan_results` into **data** directory.

Thanks for the fantastic application and I'll try help you with the knowing security problems that you write in readme.md

**Comment by cyc10n3** [comment]
Thanks for your feedback. Issue has been resolved. Hence, closing this ticket.
